### ISSUE TITLE
Add a Travis CI build

### ISSUE THREAD

**Issue by mbrukman** [JanusGraph/janusgraph.org#28]
Recommended guidelines from Jekyll: http://jekyllrb.com/docs/continuous-integration/travis-ci/

Previously, we had Travis CI builds auto-enabled, even without having a `.travis.yml` file present. I've just disabled it (since it was always failing with the default test command); we'll need to add the Jekyll-specific command by adding an appropriate `.travis.yml` file.

**Comment by FlorianHockmann** [comment]
Closing as there clearly is a `travis.yml` file on `master`. Looks like we just forgot to close this.
