### ISSUE TITLE
Align user logos via CSS for better presentation

### ISSUE THREAD

**Issue by mbrukman** [JanusGraph/janusgraph.org#37]
We need to use either an HTML table or a CSS framework to get better alignment of the logos — right now, the logos are not aligned vertically or horizontally; it should be updated to look much better.

For comparison, here are other user projects' logo pages, which look quite nice:

* [Friends of Rust](https://www.rust-lang.org/en-US/friends.html) — note the use case visible on mouseover, nice touch
* [Kubernetes](https://kubernetes.io/case-studies/)
* [Spinnaker](https://www.spinnaker.io/community/#whos-using-spinnaker)
* [Kata containers](https://katacontainers.io/) — see bottom of the page

Looks like Bootstrap CSS is one way to align those images, without using `<table>`, so that we don't have to keep updating rows, cells, and manually moving images across rows when we add new logos to the list.

**Comment by porunov** [comment]
Fixed by #64
