### ISSUE TITLE
Update janusgraph.org for 0.3.0

### ISSUE THREAD

**Issue by amcp** [JanusGraph/janusgraph.org#50]
https://docs.janusgraph.org/0.3.0
gives a 404 and docs still default to 0.2.1
@hsaputra @mbrukman

**Comment by pluradj** [comment]
@amcp see https://github.com/JanusGraph/docs.janusgraph.org/pull/29
With this and previous releases, I didn't merge the docs PR until after the vote closes.

**Comment by mbrukman** [comment]
+1 to what @pluradj said, and also, this is technically not the repo you are looking for: this is the janusgraph.org (website) repo; docs.janusgraph.org (docs) has its own repo: https://github.com/janusgraph/docs.janusgraph.org, which is where @pluradj's PR is targeted, as per his comment.
