### ISSUE TITLE
Docs still links to 0.1.0-SNAPSHOT

### ISSUE THREAD

**Issue by FlorianHockmann** [JanusGraph/janusgraph.org#8]
The _Docs_ link at the top of the page still links to: http://docs.janusgraph.org/0.1.0-SNAPSHOT/
After the release, it should now link to: http://docs.janusgraph.org/0.1.0/ or probably even better: http://docs.janusgraph.org/latest/

**Comment by mbrukman** [comment]
Fix merged and auto-deployed.
